/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#464554',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'surface-tint': '#494bd6',
        primary: '#4648d4',
        'on-primary': '#ffffff',
        'primary-container': '#6063ee',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#c0c1ff',
        secondary: '#00687a',
        'on-secondary': '#ffffff',
        'secondary-container': '#57dffe',
        'on-secondary-container': '#006172',
        tertiary: '#6b38d4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8455ef',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
        success: '#10b981', // Keeping old tokens if needed
        warning: '#f59e0b',
        danger: '#ba1a1a', // Mapped to error
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        heading: ['var(--font-hanken-grotesk)', 'var(--font-inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: '8px',
        DEFAULT: '16px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'gutter-desktop': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      animation: {
        flip: 'flip 0.6s ease-in-out',
      },
      keyframes: {
        flip: {
          '0%': { transform: 'rotateY(0deg)' },
          '100%': { transform: 'rotateY(180deg)' },
        },
      },
    },
  },
  plugins: [],
}
